// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kmr.proto

/*
Package kmrpb is a generated protocol buffer package.

It is generated from these files:
	kmr.proto

It has these top-level messages:
	RegisterParams
	ReportInfo
	Task
	TaskInfo
	Response
	KV
*/
package kmrpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReportInfo_ErrorCode int32

const (
	ReportInfo_DOING  ReportInfo_ErrorCode = 0
	ReportInfo_ERROR  ReportInfo_ErrorCode = 1
	ReportInfo_FINISH ReportInfo_ErrorCode = 2
)

var ReportInfo_ErrorCode_name = map[int32]string{
	0: "DOING",
	1: "ERROR",
	2: "FINISH",
}
var ReportInfo_ErrorCode_value = map[string]int32{
	"DOING":  0,
	"ERROR":  1,
	"FINISH": 2,
}

func (x ReportInfo_ErrorCode) String() string {
	return proto.EnumName(ReportInfo_ErrorCode_name, int32(x))
}
func (ReportInfo_ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type RegisterParams struct {
	JobName  string `protobuf:"bytes,1,opt,name=jobName" json:"jobName,omitempty"`
	WorkerID int64  `protobuf:"varint,2,opt,name=workerID" json:"workerID,omitempty"`
}

func (m *RegisterParams) Reset()                    { *m = RegisterParams{} }
func (m *RegisterParams) String() string            { return proto.CompactTextString(m) }
func (*RegisterParams) ProtoMessage()               {}
func (*RegisterParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterParams) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *RegisterParams) GetWorkerID() int64 {
	if m != nil {
		return m.WorkerID
	}
	return 0
}

type ReportInfo struct {
	TaskInfo *TaskInfo            `protobuf:"bytes,1,opt,name=taskInfo" json:"taskInfo,omitempty"`
	WorkerID int64                `protobuf:"varint,4,opt,name=workerID" json:"workerID,omitempty"`
	Retcode  ReportInfo_ErrorCode `protobuf:"varint,5,opt,name=retcode,enum=kmrpb.ReportInfo_ErrorCode" json:"retcode,omitempty"`
}

func (m *ReportInfo) Reset()                    { *m = ReportInfo{} }
func (m *ReportInfo) String() string            { return proto.CompactTextString(m) }
func (*ReportInfo) ProtoMessage()               {}
func (*ReportInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReportInfo) GetTaskInfo() *TaskInfo {
	if m != nil {
		return m.TaskInfo
	}
	return nil
}

func (m *ReportInfo) GetWorkerID() int64 {
	if m != nil {
		return m.WorkerID
	}
	return 0
}

func (m *ReportInfo) GetRetcode() ReportInfo_ErrorCode {
	if m != nil {
		return m.Retcode
	}
	return ReportInfo_DOING
}

type Task struct {
	Retcode  int32     `protobuf:"varint,1,opt,name=retcode" json:"retcode,omitempty"`
	Taskinfo *TaskInfo `protobuf:"bytes,2,opt,name=taskinfo" json:"taskinfo,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Task) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *Task) GetTaskinfo() *TaskInfo {
	if m != nil {
		return m.Taskinfo
	}
	return nil
}

type TaskInfo struct {
	JobNodeName     string `protobuf:"bytes,1,opt,name=jobNodeName" json:"jobNodeName,omitempty"`
	MapredNodeIndex int32  `protobuf:"varint,2,opt,name=mapredNodeIndex" json:"mapredNodeIndex,omitempty"`
	Phase           string `protobuf:"bytes,3,opt,name=phase" json:"phase,omitempty"`
	SubIndex        int32  `protobuf:"varint,4,opt,name=subIndex" json:"subIndex,omitempty"`
}

func (m *TaskInfo) Reset()                    { *m = TaskInfo{} }
func (m *TaskInfo) String() string            { return proto.CompactTextString(m) }
func (*TaskInfo) ProtoMessage()               {}
func (*TaskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TaskInfo) GetJobNodeName() string {
	if m != nil {
		return m.JobNodeName
	}
	return ""
}

func (m *TaskInfo) GetMapredNodeIndex() int32 {
	if m != nil {
		return m.MapredNodeIndex
	}
	return 0
}

func (m *TaskInfo) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *TaskInfo) GetSubIndex() int32 {
	if m != nil {
		return m.SubIndex
	}
	return 0
}

type Response struct {
	Retcode int32 `protobuf:"varint,1,opt,name=retcode" json:"retcode,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

type KV struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KV) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterParams)(nil), "kmrpb.RegisterParams")
	proto.RegisterType((*ReportInfo)(nil), "kmrpb.ReportInfo")
	proto.RegisterType((*Task)(nil), "kmrpb.Task")
	proto.RegisterType((*TaskInfo)(nil), "kmrpb.TaskInfo")
	proto.RegisterType((*Response)(nil), "kmrpb.Response")
	proto.RegisterType((*KV)(nil), "kmrpb.KV")
	proto.RegisterEnum("kmrpb.ReportInfo_ErrorCode", ReportInfo_ErrorCode_name, ReportInfo_ErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Master service

type MasterClient interface {
	RequestTask(ctx context.Context, in *RegisterParams, opts ...grpc.CallOption) (*Task, error)
	ReportTask(ctx context.Context, in *ReportInfo, opts ...grpc.CallOption) (*Response, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) RequestTask(ctx context.Context, in *RegisterParams, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := grpc.Invoke(ctx, "/kmrpb.Master/RequestTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) ReportTask(ctx context.Context, in *ReportInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kmrpb.Master/ReportTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Master service

type MasterServer interface {
	RequestTask(context.Context, *RegisterParams) (*Task, error)
	ReportTask(context.Context, *ReportInfo) (*Response, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_RequestTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RequestTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kmrpb.Master/RequestTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RequestTask(ctx, req.(*RegisterParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_ReportTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).ReportTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kmrpb.Master/ReportTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).ReportTask(ctx, req.(*ReportInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kmrpb.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTask",
			Handler:    _Master_RequestTask_Handler,
		},
		{
			MethodName: "ReportTask",
			Handler:    _Master_ReportTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kmr.proto",
}

func init() { proto.RegisterFile("kmr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdd, 0xce, 0x93, 0x40,
	0x10, 0x2d, 0xb4, 0xf4, 0x83, 0xe1, 0x4b, 0x8b, 0x1b, 0x4d, 0x48, 0xbd, 0x21, 0x1b, 0x2f, 0x48,
	0x54, 0x2e, 0x68, 0x7c, 0x02, 0xdb, 0x2a, 0x31, 0x6d, 0xcd, 0x6a, 0xbc, 0x5f, 0x64, 0xd4, 0x8a,
	0x74, 0xe9, 0x2e, 0xf5, 0xe7, 0x0d, 0x7c, 0x27, 0x5f, 0xce, 0xec, 0x52, 0x90, 0x6a, 0xfc, 0xee,
	0x66, 0xce, 0xce, 0x9c, 0x99, 0x73, 0x76, 0xc0, 0x2b, 0x2b, 0x99, 0xd4, 0x52, 0x34, 0x82, 0x38,
	0x65, 0x25, 0xeb, 0x9c, 0x6e, 0x60, 0xc6, 0xf0, 0xe3, 0x41, 0x35, 0x28, 0x5f, 0x73, 0xc9, 0x2b,
	0x45, 0x42, 0xb8, 0xf9, 0x2c, 0xf2, 0x1d, 0xaf, 0x30, 0xb4, 0x22, 0x2b, 0xf6, 0x58, 0x97, 0x92,
	0x05, 0xb8, 0xdf, 0x84, 0x2c, 0x51, 0x66, 0xab, 0xd0, 0x8e, 0xac, 0x78, 0xcc, 0xfa, 0x9c, 0xfe,
	0xb2, 0x00, 0x18, 0xd6, 0x42, 0x36, 0xd9, 0xf1, 0x83, 0x20, 0x8f, 0xc1, 0x6d, 0xb8, 0x2a, 0x75,
	0x6c, 0x58, 0xfc, 0x74, 0x9e, 0x98, 0x81, 0xc9, 0xdb, 0x0b, 0xcc, 0xfa, 0x82, 0x2b, 0xde, 0xc9,
	0x35, 0x2f, 0x79, 0x06, 0x37, 0x12, 0x9b, 0xf7, 0xa2, 0xc0, 0xd0, 0x89, 0xac, 0x78, 0x96, 0x3e,
	0xbc, 0xf0, 0xfc, 0x19, 0x96, 0xac, 0xa5, 0x14, 0xf2, 0xb9, 0x28, 0x90, 0x75, 0xb5, 0xf4, 0x29,
	0x78, 0x3d, 0x4a, 0x3c, 0x70, 0x56, 0xfb, 0x6c, 0xf7, 0x22, 0x18, 0xe9, 0x70, 0xcd, 0xd8, 0x9e,
	0x05, 0x16, 0x01, 0x98, 0x6e, 0xb2, 0x5d, 0xf6, 0xe6, 0x65, 0x60, 0xd3, 0x2d, 0x4c, 0xf4, 0x5e,
	0x5a, 0x7b, 0x37, 0x4d, 0x6f, 0xed, 0xf4, 0x84, 0x9d, 0xa0, 0x83, 0x16, 0x64, 0xdf, 0x21, 0x48,
	0x17, 0xd0, 0x9f, 0x16, 0xb8, 0x1d, 0x4c, 0x22, 0xf0, 0xb5, 0x81, 0xa2, 0xc0, 0x81, 0xa7, 0x43,
	0x88, 0xc4, 0x30, 0xaf, 0x78, 0x2d, 0xb1, 0xd0, 0x48, 0x76, 0x2c, 0xf0, 0xbb, 0x19, 0xe1, 0xb0,
	0xbf, 0x61, 0x72, 0x1f, 0x9c, 0xfa, 0x13, 0x57, 0x18, 0x8e, 0x0d, 0x4b, 0x9b, 0x68, 0xff, 0xd4,
	0x39, 0x6f, 0x1b, 0x27, 0xa6, 0xb1, 0xcf, 0xe9, 0x23, 0x70, 0x19, 0xaa, 0x5a, 0x1c, 0x15, 0xfe,
	0x5f, 0x1d, 0x7d, 0x02, 0xf6, 0xab, 0x77, 0x24, 0x80, 0x71, 0x89, 0x3f, 0xcc, 0xdb, 0x2d, 0xd3,
	0xa1, 0x9e, 0xf7, 0x95, 0x7f, 0x39, 0xa3, 0xd9, 0xe7, 0x96, 0xb5, 0x49, 0x7a, 0x82, 0xe9, 0x96,
	0xeb, 0x8b, 0x21, 0x4b, 0xf0, 0x19, 0x9e, 0xce, 0xa8, 0x1a, 0x63, 0xdf, 0x83, 0xfe, 0x6f, 0x86,
	0x17, 0xb5, 0xf0, 0x07, 0x4e, 0xd1, 0x11, 0x49, 0xbb, 0x4b, 0x31, 0x3d, 0xf7, 0xfe, 0xf9, 0xcf,
	0xc5, 0xbc, 0x87, 0xda, 0xc5, 0xe9, 0x28, 0x9f, 0x9a, 0xa3, 0x5d, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x37, 0xfc, 0x01, 0xbe, 0xc1, 0x02, 0x00, 0x00,
}
